osx_image: xcode11
language: objective-c
script:
- set -o pipefail
- xcodebuild -project Example/ParallaxOverlayExample.xcodeproj -scheme ParallaxOverlayExample
  -sdk iphonesimulator -destination 'OS=13.0,name=iPhone XÊ€,platform=iOS Simulator'
  -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c
