osx_image: xcode11.3
language: objective-c
env:
  global:
  - FRAMEWORK_NAME=ACKImagePicker
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current --cache-builds
- carthage archive $FRAMEWORK_NAME
after_deploy:
- pod trunk push
script:
- set -o pipefail
- xcodebuild -project ACKImagePicker.xcodeproj -scheme ACKImagePickerExample
  -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.3'
  -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint
deploy:
  provider: releases
  api_key:
    secure: KEFJr4N4kMcWjnHPxm16fLQRKk3qF9vPHO+3JezTutNh5Ty7xQ/3jz1/92VuA1o6/n4LNiJm3APQGxYkqXE4UEPBIIUtuMDgIVRDJviCwZTPFUaB8MsoyZZfme+PgQRFUY1F7Cowi7XaNI7Ok3eS2GPLYsE4kDRKlW3OGGXP2Q2kOSXUTvjqM1zk/cYqw3oQMZ06vRz/oYnvrigaPgEooJaOyq4MefzinLWZOqmait91E0FxZ0Y4041+NRnT1MB0WEbeQBvFwAzjbV88Ab30Jl0HueukWz/MJHA/GQLKa6zKdPHV0HYr03udLmgZv1nlGMVJtkf4A3eIBMMFjWSQNnmD07/EsFXQSDpVaoXGok5Atok1o6B9ptMF/26W0mFZmd2LvZ+pSJ2vPqk+/U5SLeMQOFxheoZjs8Lj3ikKQCHHDxHNbA+IrYzYQGfWQLcF7huSFvL3lojqPK5RAQDF02iJ7Rjmks2aTx2czqx3HTdWkH4QZMKefO8VEihoJzuUFThGv11Md6Tu5eV49UPR9tgYzTGR2BXdSu5LdZ1Td5ok9+xLA6hI4LPEBQcKZbHAUV/Eozj2YnUNuMrstZpAz1MvxsTLPKz9h4eyvc1AuiVlg2XUh++AxJHPhf8YecHSgVj1fMU4AozWE6nJX1gWoyl7uOHREAGJqEyLWpe6N/M=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: AckeeCZ/ACKImagePicker
    tags: true