name: Build

on: [pull_request, push]

jobs:
  tests:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AckeeCZ/load-xcode-version@1.0
      - name: Build Carthage binary
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: carthage build --platform iOS --cache-builds --no-skip-current